project:
  type: website

website:
  title: "Maria Pope"
  navbar:
    background: light
    foreground: dark
    search: true
  
    left:
      - href: index.qmd
        text: Home
      - pages/publications.qmd
      - cv.qmd
      - pages/about.qmd
  page-footer:
        right:
        - icon: envelope
          href: https://mailto:popeme@iu.edu 
        - icon: github
          href: https://github.com/popeme
        - icon: twitter 
          href: https://twitter.com/MariaEPope1 
      

format:
  html:
    theme: solar
    css: styles.css
    toc: true



